### ISSUE TITLE
Design a system for dynamic hooks

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#1138]
Why not use interface module to replace hard coded hooks. We could create new custom types for special fields such as monaco editor

**Comment by antonmihaylov** [comment]
For dynamic hooks:
- Hooks will use the same structure as Atoms (the api Interface for props)
- The manual way is more verbose initially since code must be written for: backend config interface, zod validation schema, graphql model, frontend form schema

Against dynamic hooks:
- We don't have that many hooks, so we won't 'loose' a lot of verbosity by writing config for each of them
- We need to make our type module more advanced to handle the forms, we would need to implement:
    - Validations, required fields
    - Monaco field type, with monaco configuration (Graphql, Json)
    - Integrate the monaco graphql field to read the URL from the other form field (in Graphql query and mutation hooks)
    - Page field type, to display a SelectPage field
- The hooks directly depend on the config's API. Making the API dynamically in runtime has no benefit for the application since we'd need to seed it in the exact same structure the hooks expect and migrate it every time the code for the hooks changes.
