### ISSUE TITLE
Refactor graph creation logic

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#1229]
Say we have a tree that we want to parse, what would be the most logical way to go through each node?

We could use a recursive loop, but why not utilize the advantage of graph concepts?

---

We could use breadth first search to queue up operations, which would process nodes in order from root to leaf. Then we can call a reduce to create a single graph.

https://github.com/codelab-ai/codelab.ai/blob/6b053ffa83a927a1382738d004da3eef261bc716/libs/backend/modules/element/src/use-cases/element/create-element/element-mutation.factory.ts#L204-L223

This can be replaced by a BFS reduce call

https://github.com/codelab-ai/codelab.ai/blob/7a2baec698358f5e36ddc6a79bd7b9f0be4848c4/libs/backend/modules/tag/src/use-cases/import-tags/import-tags.service.ts#L42-L85

We could ignore the iteration count for now as it likely won't ever reach to a level that is prohibitive

**Comment by antonmihaylov** [comment]
Can you elaborate a bit on the goal

> We could use breadth first search to queue up operations, which would process nodes in order from root to leaf.
This is exactly what's going on in ElementMutationFactory 

The difference between that is that  in ImportTagsService the input is in our Graph interface form {vertices: [], edges:[])
While in ElementMutationFactory it's in nested form. Correct me if I'm wrong, but the complexity of converting one to another is not worth the benefit of being able to use treeProvider on it, because the same traversal will be needed, on top of bfs then.

**Comment by webberwang** [comment]
We're referring to the exported elements data?  Exported data should actually be in graph form so we could use the same approach as Tag

**Comment by antonmihaylov** [comment]
The children input property was first introduced as a means to attach components as children to the created element, not for importing. But it's not needed anymore, since I changed that logic a bit in #1219 
So the original idea had nothing to do with a graph input
