### ISSUE TITLE
Setup web server

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#255]
## Ambassador mapping

Currently Ambassador has a mapping using prefix url & we access our site using `http://codelab.ai/web/`

<img width="913" alt="Ambassador_Edge_Stack_Edge_Policy_Console" src="https://user-images.githubusercontent.com/26264925/98190438-dffc9980-1ecb-11eb-9ec4-02f1b2a73ce4.png">

Instead we want to access our web service using `http://codelab.ai`

## Nginx Server

Our web server requests `/_next`, but file is located in `/.next`, will need Nginx configurations

<img width="942" alt="https___codelab_ai_web_" src="https://user-images.githubusercontent.com/26264925/98190593-336ee780-1ecc-11eb-9b8d-7e73aecfc2d2.png">

You can see our CSS resources are not served

## How to run

Currently run `yarn kube:apply` to apply our kustomize settings

## Current setup

We have a multi-container pod with nginx & web service setup, digital ocean load balancer proxies to ambassador edge proxy (acting as kubernetes ingress controller), which gives us access to our web service pod consisting of 2 containers.

**Comment by nutshell113** [comment]
@webberwang :

It caused by you used prefixes routed instead of virtual-hosts routed, now they are fixed:
![image](https://user-images.githubusercontent.com/16603476/98683919-2bb1b600-2398-11eb-9f65-ac4287578fc3.png)

Staging endpoint: https://staging.codelab.ai 
Production endpoint: https://codelab.ai

Please see and merge it: https://github.com/codelab-ai/codelab.ai/pull/278
