### ISSUE TITLE
Component module with DGraph

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#826]
- Think about removing Atom/AtomType, and coming up with a system for sharing Component created by Admin
- Access Control, add $ROLE to Auth0

**Comment by antonmihaylov** [comment]
To better suit dgraph we need to modify our ER (btw - not only for components, need to model the other parts too)

Since we can utilize native nodes and edges, I suggest we drop `ComponentElements` and `ComponentLinks` and just use a unified `Component` entity, like so:

![image](https://user-images.githubusercontent.com/57956282/117578301-58038080-b0f6-11eb-8d2c-bf1a6cecae18.png)

It has everything we need in a single reusable entity. 
1. We can construct an entire tree by traversing its `childrens` property. 
2. We can render a leaf node by using its `atom` property. 
3. We can render a node and their children if it has both `atom` property and `childrens` property
