### ISSUE TITLE
Explorer GraphQL Proxy Strategies for Authorization

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#834]
There's a couple ways we could add a Nest.js GraphQL Auth layer..

1. We could construct our own GraphQL schema, then in the resolvers, we call DGraph API that way. This seems a bit verbose however
2. We could use Apollo federation to merge the schemas together. A bit more complicated, I'm not 100% sure how this would work.
3. We could use Nestjs as an API proxy, so we just add an Auth layer & just forward the API call to DGraph. Seems to be the simplest approach, but authorization wouldn't be able to be done on the field level.

Let me know if you think of any other approaches

**Comment by antonmihaylov** [comment]
Did some research on this, looked into other options like stitching the schema or somehow reusing the same schema from dgraph, or proxying the request somehow, but nothing of that looked decent. Here are the pros/cons of the options:

### 1. Dgraph as a database layer: Next -> Nest -> (dql and graphql) Dgraph 

- Pros: 
  - We have total control over our application - custom validation, authentication, authorization guards, etc. It's much easier to work on this in nest.js rather than in the dgraph schema.graphql file.
  - Our nest.js will be our public API, if we define the API schema correctly, we can freely refactor the backend however we want later on - if we, later on, need it - we can move the entire user model to hasura or just a regular Postgres with some orm 
  - Maybe we could stitch the remote schema using nests, here's an [example with Hasura](https://stackoverflow.com/questions/54481645/how-to-get-multiple-remote-schemas-stitched-with-nestjs-and-apollo-server)
  - We can move some of our logic to nest, spare our frontend some work
- Cons:
  - Too verbose, that was the whole reason we went from prisma to hasura. This can be minified by using graphql to talk to Dgraph (when we can) - we can use codegen for that and the rest is just connecting the resolver to the appropriate dgraph generated method and defining the input and output types. But since a lot of our queries would need to be in dql, it's not much of a benefit

### 2. Apollo federation

- This seems more like a tool for graphql microservices, we would still need to define a schema for our nest.js app and custom resolvers, with the added complexity of federation. I don't see a benefit over option 1.

### 3. Nestjs as a simple proxy

- We might as well do that in next.js, we're already proxying it through it. Pretty straightforward, but I think options 1 and 4 are superior in every way, except simplicity. And we can't really do anything with that, only authentication, which we already have in dgraph

### 4. Dgraph as a middleman: Next -> (graphql) Dgraph -> Nest/Lambda

- Directly access Dgraph /graphql from next.js, simple graphql crud can be done through the readily available dgraph graqphql API
- Remove access to dql endpoints, except for our nest app / lambdas. Note: *I didn't found any way to do this at the application level. There are options for the cloud version (api keys) and ACL for the enterprise plan, but the only option for self-hosted seems to be blocking it in the infrastructure layer with [reverse proxy configuration](https://discuss.dgraph.io/t/authorization-for-dql/10181/3). Is this viable? Why doesn't a database has propper access control?* 
- Add a nest.js api server or a set of lambdas that will serve as our backend logic layer. They will access dgraph directly and query it using dql (or graphql?). Note that our nest.js app doesn't need to serve graphql, but a regular rest-like API, which makes it a bit easier to manage than option 1
- Use [dgraph custom directive](https://dgraph.io/docs/graphql/custom/directive) to route the request to the nest.js api or lambda and turn that into a graphql field. Do whatever we want inside the nest.js api / lambda. Perhaps use [dgraph lambda](https://dgraph.io/docs/graphql/lambda/overview) to manage the lambda infrastructure. But nest has the advantage of a clean architecture

- Pros:
  - Simpler - we have the auto generated dgraph graphql readily available for next.js to consume
  - One graphql api unifies everything
- Cons:
  - We will need custom resolvers for validation, advanced authorization, getting properties from edges (not supported in dgraph's grpahql) and any recursive graph queries. My guess is that this will be more than half of our queries.  Since we still have to provide custom input and output types, custom resolvers, custom infrastructure for them, given the weird wiring of the whole thing (urls and request bodies in a @custom directive) and the fact that dgraph has some features missing and it's relatively fresh (new problems might arise that we don't see now), is this worth more than the time it will take to go with option 1? Is it not a safer bet to put a layer before dgraph?
  - The only protection of our dql endpoint being reverse proxy configurion could be prone to some security errors (not sure on that point, but If it weren't the case, why is it a standard to have username and password authentication in Postgres?)



Relevant threads:

https://discuss.dgraph.io/t/the-auth-directive-graphql/9748/15 - confirmation that @auth doesn't work in dql queries

https://discuss.dgraph.io/t/wip-auth-rules-custom-dql-query/13926 - 14d ago - @auth in dql is in the works

https://discuss.dgraph.io/t/dgraph-product-roadmap-2021/12284 - product roadmap doesn't mention @auth in dql anywhere, but has nice stuff like post-update auth rules and field-level Auth 

https://discuss.dgraph.io/t/dql-queries-need-to-respect-graphql-auth-rules/10481 - discussion on how to protect dql queries, best way suggested is reverse proxy configuration

https://discuss.dgraph.io/t/discussion-improving-the-graphql-implementation-for-it-to-be-useful-in-real-production-apps/13850  - great points on why Dgraph should NOT be used directly by the frontend client in production and requires an backend to act as a middleman api

https://discuss.dgraph.io/t/field-validations/11352/7 - discussion on validation - great point on the fact that we can't do backend validation with dgraph. We used to be able with Hasura, since you have constrains built into sql. But now the only validation we can do is "required", and it's enforced by graphql. One of dgraph's team keeps insisting that backend validation is not necessary (??). The dgraph team seems to be sending out very mixed messaged ranging for the purpose of dgraph, ranging from "it's a DB, can't include app layer logic in it" and "it's the full package, you can directly connect it to your frontend" 


In my opinion - option 4 would be the best way to go if we were doing a simpler application, where most of the things are simple CRUD that can be handled by the auto-generated graphql. 
Since we have a lot of recursive graphs and logic attached to them, I think option 1 is our safest bet. And we can easily adapt to other dgraph problems or missing features that we find, since it's still relatively new
