### ISSUE TITLE
Primitive Rename

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/codelab.ai#932]
- [ ] I think following code vocabulary we would name `PrimitiveType` instead of `SimpleType`, for the enum we could use `PrimitiveKind`

As our own naming convention, we could use `Kind` affix to denote enums.

<img width="283" alt="schema_graphql_—_codelab" src="https://user-images.githubusercontent.com/26264925/125070703-2f075980-e06d-11eb-87d2-666bb9895759.png">

- [ ] Why is this needed again?

<img width="478" alt="schema_graphql_—_codelab" src="https://user-images.githubusercontent.com/26264925/125074012-98896700-e071-11eb-9ef7-66dcd7810e2c.png">

**Comment by antonmihaylov** [comment]
PrimitiveType does sound better

Atom on Interface does seem weird, I should've added a comment.
It's the inverse of Atom.propTypes
![image](https://user-images.githubusercontent.com/57956282/125079913-d4054f00-e0cc-11eb-8d0b-5583a9fa9612.png)

It is needed when deleting an Interface. If we delete an interface that is used as propTypes of an Atom, our data will be corrupt, because Atom.propTypes is required

![image](https://user-images.githubusercontent.com/57956282/125080104-129b0980-e0cd-11eb-9dd6-488395a89e8a.png)

**Comment by webberwang** [comment]
Why not do Atom.Type instead of Atom.Interface. Type is the more abstract form right?

**Comment by antonmihaylov** [comment]
It is, but it doesn't make much sense to pass any other type except Interface as props to Atom, because we always pass an object as props

**Comment by antonmihaylov** [comment]
For clarification - propTypes is the Atom's API

**Comment by antonmihaylov** [comment]
via Hubstaff
User: Anton Mihaylov

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/09/21 - 07/09/21
Work session total: 1:50:49
Billable: Yes

Grand total: 1:50:49

**Comment by antonmihaylov** [comment]
via Hubstaff
User: Anton Mihaylov

Project: codelab.ai - https://app.hubstaff.com/projects/1192287
Date Range: 07/09/21 - 07/09/21
Work session total: 0:08:34
Billable: Yes

Grand total: 1:59:23
